name: 'OVH DNS'
description: 'Upsert or delete an OVH DNS entry'
author: 'Solinum'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  applicationKey:
    description: 'OVH Application Key'
    required: true
  applicationSecret:
    description: 'OVH Application Secret'
    required: true
  consumerKey:
    description: 'OVH Consumer Key'
    required: true
  endpoint:
    description: 'OVH Endpoint'
    required: true
    default: 'ovh-eu'
  zone:
    description: 'The zone of the DNS entry'
    required: true
  subDomain:
    description: 'The subdomain of the DNS entry'
    required: true
  target:
    description: 'The target of the DNS entry, required if present is true'
  present:
    description: 'Should this record be present or absent'
    required: true
    default: 'true'
  type:
    description: 'The type of the DNS entry'
    required: true
    default: 'CNAME'
  ttl:
    description: 'The TTL of the DNS entry'
    required: false
    default: '600'

# Define your outputs here.
outputs:
  record:
    description: 'The updated DNS record, if present is true'

runs:
  using: node20
  main: dist/index.js
